accounts/urls.py
from django.urls import path

from .views import home_view, login_view, logout_view, ActivateAccountView, RegisterView

urlpatterns = [
    path('', home_view, name="home"),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<str:username>/<str:token>', ActivateAccountView.as_view(), name='activate')
]

app_name = "accounts"

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
]

templates/base/_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  {% block link %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
  {% endblock %}

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'accounts:home' %}" class="nav-link px-2 text-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 text-white">About</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
        <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..."
               aria-label="Search">
      </form>

    <div class="text-end">
        {% if request.user.is_authenticated %}

        <button type="button" onclick="location.href='{% url 'accounts:logout' %}'" class="btn btn-outline-light me-2">Logout</button>

        {% else %}
        <button type="button" onclick="location.href='{% url 'accounts:login' %}'" class="btn btn-outline-light me-2">Login</button>
        <button type="button" onclick="location.href='{% url 'accounts:register' %}'" class="btn btn-warning">Sign-up</button>
        {% endif %}
      </div>
    </div>
  </div>
</header>

<div class="container mt-5">
  {% include 'base/notifications/_messages.html' %}
  {% block content %}
  {% endblock %}
</div>
{% block script %}
  <script src="{% static 'js/close_messages.js' %}"></script>
{% endblock %}
</body>
</html>